"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

load_dotenv('/home/lien/NLP/dj-fullstack-galore/app_rag/.env', 
            override=True)

# if os.path.isfile('env.py'):
#     import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-)gr8#nstt%y(j&jc9(*q&c(%@b5vqi-obw56qeb@6@%@)x)n=b'
# SECRET_KEY = os.environ.get('SECRET_KEY')

SECRET_KEY = str(os.getenv('SECRET_KEY'))

OPENAI_API_KEY = str(os.getenv('OPENAI_API_KEY'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_summernote',
    'about',
    'app_rag',
    'import_export',
    'landing',
    'leaflet_app',
    'map_app',
    'widget_tweaks',
]

SITE_ID = 1
# So that Django can handle multiple sites from one database.
# We need to give each project an ID value so that the database
# is aware of which project is contacting it.
# We only have one site here using our one database,
# but we'll still need to tell Django the site number of 1 explicitly.

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
# The redirection URLs are also added so that after we've logged in or 
# logged out, the site will automatically redirect to the home page.

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'
# These constants set bootstrap5 as the allowed template pack and as the
# default template pack for project.
# This choice of default template pack is to match the Bootstrap5 CSS and JS
# files already used in project base.html template.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'my_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    #'default': {},
    'default': {
         'ENGINE': 'django.db.backends.postgresql_psycopg2',
         'NAME': 'vector_db',
         "USER": "lien",
         "PASSWORD": "1212",
         # "HOST": "localhost",
         # "PORT": 5432,
     },
    'projectdb': {
         'ENGINE': 'django.db.backends.sqlite3',
         'NAME': BASE_DIR / 'db.sqlite3',
     },
    'geospatial': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'geospatial_db',
        'USER': 'geospatial_user',
        'PASSWORD': '1212',
        # 'HOST': 'localhost',
        # 'PORT': '5432',
    },
 }


CSRF_TRUSTED_ORIGINS = [
    'https://*.127.0.0.1',
 ]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
ACCOUNT_EMAIL_VERIFICATION = 'none'
# We are not using email verification in this project, so this line informs
# Django not to expect it. Without this line, you would get Internal Server
# errors (code 500) during login and registration.

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# For file uploads:
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

LOGIN_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'