# Generated by Django 5.0.7 on 2024-08-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='address',
            field=models.CharField(help_text='Enter location...', max_length=100, null=True, unique=True),
        ),
    ]
