# Generated by Django 5.0.7 on 2024-08-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0002_alter_search_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['address', 'date']},
        ),
    ]
