# Generated by Django 5.0.7 on 2024-08-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rag', '0003_document_alter_loadimage_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loadimage',
            table='Images',
        ),
    ]
