# Generated by Django 5.0.7 on 2024-09-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='trip',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
