# Generated by Django 5.0.7 on 2024-08-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_app', '0002_alter_trip_end_date_alter_trip_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(),
        ),
    ]
