# Generated by Django 5.0.7 on 2024-08-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_app', '0003_alter_trip_end_date_alter_trip_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='lat',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='lon',
            field=models.CharField(),
        ),
    ]
