# Generated by Django 5.0.7 on 2024-08-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_app', '0005_alter_trip_lat_alter_trip_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='lon',
            field=models.FloatField(blank=True),
        ),
    ]
