# Generated by Django 5.0.7 on 2024-08-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_app', '0006_alter_trip_lat_alter_trip_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='lon',
        ),
    ]
