# Generated by Django 5.0.7 on 2024-08-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_app', '0007_remove_trip_lat_remove_trip_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
